language: php

sudo: true

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
env:
  - DB=mysql

before_script:
  - ./tests/travis/prepare.sh
  - composer self-update
  - composer install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover
